theme: jekyll-theme-minimal
plugins:
  - "jekyll-github-metadata"

domain: elapuestojoe.github.com
author: Kevin Islas.
email: elapuestojoe@github.com

repository: elapuestojoe/ziknet-trends.github.io

title: "Ziknet-Trends"
description: "Ziknet-Trends website"